### ISSUE TITLE
TabLayout求拓展

### ISSUE THREAD

**Issue by kunandkun** [hongyangAndroid/AndroidAutoLayout#107]
您好,我拓展了继承TabLayout的类AutoTabLayout，在autolayoutActivity里增加了适配。我现在急需使用,求大神再赶紧更新一下吧。但 @TargetApi(Build.VERSION_CODES.LOLLIPOP)
 public AutoTablayout(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr,defStyleRes);
    }方法super方法里面传不了四个参数.

package com.zhy.autolayout;

import android.content.Context;
import android.support.v7.app.AppCompatActivity;
import android.util.AttributeSet;
import android.view.View;

;

/**
- Created by zhy on 15/11/19.
  */
  public class AutoLayoutActivity extends AppCompatActivity
  {
  private static final String LAYOUT_LINEARLAYOUT = "LinearLayout";
  private static final String LAYOUT_FRAMELAYOUT = "FrameLayout";
  private static final String LAYOUT_RELATIVELAYOUT = "RelativeLayout";
  private static final String LAYOUT_TABLAYOUT = "Tablayout";
  
  @Override
  public View onCreateView(String name, Context context, AttributeSet attrs)
  {
      View view = null;
      if (name.equals(LAYOUT_FRAMELAYOUT))
      {
          view = new AutoFrameLayout(context, attrs);
      }
  
  ```
  if (name.equals(LAYOUT_LINEARLAYOUT))
  {
      view = new AutoLinearLayout(context, attrs);
  }
  
  if (name.equals(LAYOUT_RELATIVELAYOUT))
  {
      view = new AutoRelativeLayout(context, attrs);
  }
  if (name.equals(LAYOUT_TABLAYOUT))
  {
      view = new AutoTablayout(context, attrs);
  }
  
  if (view != null) return view;
  
  return super.onCreateView(name, context, attrs);
  ```
  
  }

}

package com.zhy.autolayout;

import android.annotation.TargetApi;
import android.content.Context;
import android.os.Build;
import android.support.design.widget.TabLayout;
import android.util.AttributeSet;
import android.view.ViewGroup;

import com.zhy.autolayout.utils.AutoLayoutHelper;

public class AutoTablayout extends TabLayout {
    private final AutoLayoutHelper mHelper = new AutoLayoutHelper(this);

```
public AutoTablayout(Context context) {
    super(context);
}

public AutoTablayout(Context context, AttributeSet attrs) {
    super(context, attrs);
}

public AutoTablayout(Context context, AttributeSet attrs, int defStyle) {
    super(context, attrs, defStyle);
}

@TargetApi(Build.VERSION_CODES.LOLLIPOP)
public AutoTablayout(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
    super(context, attrs, defStyleAttr);
}

@Override
public LayoutParams generateLayoutParams(AttributeSet attrs) {
    return new LayoutParams(getContext(), attrs);
}

@Override
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
    if (!isInEditMode())
        mHelper.adjustChildren();
    super.onMeasure(widthMeasureSpec, heightMeasureSpec);
}

@Override
protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
    super.onLayout(changed, left, top, right, bottom);
}


public static class LayoutParams extends TabLayout.LayoutParams
        implements AutoLayoutHelper.AutoLayoutParams {
    private AutoLayoutInfo mAutoLayoutInfo;

    public LayoutParams(Context c, AttributeSet attrs) {
        super(c, attrs);
        mAutoLayoutInfo = AutoLayoutHelper.getAutoLayoutInfo(c, attrs);
    }

    public LayoutParams(int width, int height) {
        super(width, height);
    }

    public LayoutParams(ViewGroup.LayoutParams source) {
        super(source);
    }

    public LayoutParams(MarginLayoutParams source) {
        super(source);
    }

    @Override
    public AutoLayoutInfo getAutoLayoutInfo() {
        return mAutoLayoutInfo;
    }


}
```

}

**Comment by wei3** [comment]
我也是遇到楼上的tabLayout 问题，按照你的demo ,发现tablayout的字体得不到适配，比正常的px值小很多，请问大神有好的办法吗

**Comment by longpenghn** [comment]
楼上问题，在tablayout中使用自定义布局级，代码中动态设置textsize即可解决

**Comment by fanturbo** [comment]
哈哈，忽然搜到这个问题，早就有了，为啥都没有看到呢。。https://github.com/hongyangAndroid/AndroidAutoLayout/blob/e29298201f2b02754de5edd0b7957ad361a56f69/autolayout-widget/src/main/java/com/zhy/autolayout/widget/AutoTabLayout.java
