### ISSUE TITLE
报错Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by swxca** [hongyangAndroid/AndroidAutoLayout#109]
我的activity继承自AutoLayoutActivity就会报这个错，继承自Activity就没事。而且系统给我的报错对应的行数也不正确，检查了一遍xml文件也没有错。

**Comment by swxca** [comment]
已解决。<meta-data>标签一定要放在Application里面。

**Comment by yasb001** [comment]
@swxca 能贴一下代码吗？我刚接触Android，不太懂你的解决办法。
