### ISSUE TITLE
分辨率相同、屏幕大小不同时，适配出来的效果不一样！！

### ISSUE THREAD

**Issue by ijustyce** [hongyangAndroid/AndroidAutoLayout#128]
我大概看了源码，您是按分辨率来适配，我来举个例子，分辨率相同，但是屏幕尺寸不同，这时候dpi就不同，如果还按照您的方法，适配出来就有问题了！我亲测如此，同样是1920x1080的华为荣耀6plus和vivo x5 pro,前者 5.5寸屏幕，后者5.2存屏幕，适配出来就有点问题了。

**Comment by sunyuanfei** [comment]
你有解决吗？？

**Comment by sunyuanfei** [comment]
方便的话 回复下 我也是 也有按根据宽高比设计的

**Comment by ijustyce** [comment]
我无法解决，加上并不支持data binding ，所以自己实现了，也很简单。你可以看看 https://blog.ijustyce.win/post/%E5%9F%BA%E4%BA%8EDataBinding%E5%AE%9E%E7%8E%B0%E7%9A%84%E8%87%AA%E5%8A%A8%E5%B8%83%E5%B1%80.html 跟这个相比性能会更好点，但必须要用data binding才可以！
