### ISSUE TITLE
如果是一个正方形，用这框架后就不是正方形了

### ISSUE THREAD

**Issue by yangzhenqi** [hongyangAndroid/AndroidAutoLayout#172]
如果控件是正方形的话，用autolayout换算之后，控件就不是正方形了~这个怎么解决呢

**Comment by 289582077** [comment]
@yangzhenqi app:layout_auto_basewidth="height"，代表height上编写的像素值参考宽度。

app:layout_auto_baseheight="width"，代表width上编写的像素值参考高度。

**Comment by Yanzlllll** [comment]
sb

**Comment by 289582077** [comment]
@Yanzlllll 这就是你骂别人的理由？

**Comment by yangzhenqi** [comment]
看到了，谢谢 @289582077
