### ISSUE TITLE
480x800的时候好像有问题

### ISSUE THREAD

**Issue by cwenlu** [hongyangAndroid/AndroidAutoLayout#19]
第一个例子“新增旅客”在480x800的时候好像有问题

**Comment by hongyangAndroid** [comment]
效果图~效果图~ps:不要在模拟器（Genymotion）2.x的版本上实验，对于系统的FrameLayout内部的margin无效（具体原因未知），真机我实在是找不到~~ 你可以更改个高版本API的设备尺寸测试， 反馈个图~thx  我这边测试没有问题。

**Comment by cwenlu** [comment]
可能我搞错了，那个预览估计不对
