### ISSUE TITLE
解决AutoLayoutHelper判断是否为px时抛出警告的问题

### ISSUE THREAD

**Issue by DTHeaven** [hongyangAndroid/AndroidAutoLayout#22]
建议判断方式改为如下：

int index = array.getIndex(i);
if (!isPxVal(array.peekValue(index))) continue;

 private static boolean isPxVal(TypedValue val) {
        if (val != null && val.type == TypedValue.TYPE_DIMENSION && 
                getComplexUnit(val.data) == TypedValue.COMPLEX_UNIT_PX) {
            return true;
        }
        return false;
    }

    private static int getComplexUnit(int data) {
        return TypedValue.COMPLEX_UNIT_MASK & (data>>TypedValue.COMPLEX_UNIT_SHIFT);
    }

**Comment by cunxinaimei** [comment]
赞一个，确实比我写的好多了，不仔细看TypedValue源码还真写不出这个代码
