### ISSUE TITLE
适配问题，demo的UI显示不正确，android版本：4.2.2

### ISSUE THREAD

**Issue by VindroidH** [hongyangAndroid/AndroidAutoLayout#24]
AutoLayoutDemoForEclipse，运行在 1920*1080 强制横屏的平板上，PayFragment的 RadioButton 布局文件设置为 50px*50px 但实际显示中却为 88px*28px。

试了下，如果把Manifest中的宽高对调显示就没问题了，但是对于一个apk要在手机和平板上都通用的情况，这个问题看样子还是会有问题。无论分辨率比如何，一个50px*50px的正方形不论在什么情况下都应该显示为正方形吧？

![device-2015-12-10-094915](https://cloud.githubusercontent.com/assets/13214452/11704606/1105718c-9f24-11e5-8a4d-0863d133c18c.png)

**Comment by hongyangAndroid** [comment]
readme中又如下描述：

```
指定设置的值参考宽度或者高度

由于该库的特点，布局文件中宽高上的1px是不相等的，于是如果需要宽高保持一致的情况，布局中使用属性：

app:layout_auto_basewidth="height"，代表height上编写的像素值参考宽度。

app:layout_auto_baseheight="width"，代表width上编写的像素值参考高度。

如果需要指定多个值参考宽度即：

app:layout_auto_basewidth="height|padding"

用|隔开，类似gravity的用法，取值为：

width,height
margin,marginLeft,marginTop,marginRight,marginBottom
padding,paddingLeft,paddingTop,paddingRight,paddingBottom
textSize.
```

还有平板和手机应该不可能一套设计图吧~~~
