### ISSUE TITLE
列表适配问题

### ISSUE THREAD

**Issue by ehaahe** [hongyangAndroid/AndroidAutoLayout#28]
两台手机，一台小米note1080*1920分辨率，不带虚拟按键；一台五太子1080*1920分辨率，带虚拟按键，不知道为什么小米note上的listview总是滑不到最底部，总是被底部的控件遮盖住item高度的40%左右，老大这是什么问题呢？

**Comment by hongyangAndroid** [comment]
直接运行sample，里面包含listview的例子，如果有问题，发下对比的截图吧。

**Comment by ehaahe** [comment]
![image](https://cloud.githubusercontent.com/assets/9740081/11781199/0cc2a108-a2a3-11e5-96a2-12811d3fd135.png)
这个是什么问题？运行sample出现的

**Comment by ehaahe** [comment]
貌似和例子有点不一样，例子最底部没有控件，而且是activity，我的是fragment，最底部属于activity，下面是对比图，左边是小米note

**Comment by ehaahe** [comment]
![image](https://cloud.githubusercontent.com/assets/9740081/11781751/f63ea612-a2a6-11e5-92ac-e17d22d4b45c.png)
![image](https://cloud.githubusercontent.com/assets/9740081/11781761/09353d3a-a2a7-11e5-8008-8a2904d91ba9.png)

**Comment by hongyangAndroid** [comment]
感觉是你布局文件的问题，贴一下吧。

**Comment by ehaahe** [comment]
<?xml version="1.0" encoding="utf-8"?>
<com.zhy.autolayout.AutoFrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="100px"
        android:layout_gravity="center_horizontal"
        android:background="#FFFFFF"
        android:gravity="center"
        android:text="@string/title_zl"
        android:textColor="#1A1A1A"
        android:textSize="38px" />

    <TextView
        android:id="@+id/tv_frag_zl_record"
        android:layout_width="wrap_content"
        android:layout_height="100px"
        android:layout_gravity="right"
        android:drawablePadding="10px"
        android:drawableRight="@drawable/ic_nb_pen"
        android:gravity="center"
        android:paddingRight="20px"
        android:text="@string/title_zl_right"
        android:textColor="#808080"
        android:textSize="24px" />

    <TextView
        android:id="@+id/tv_frag_zl_art"
        android:layout_width="375px"
        android:layout_height="70px"
        android:layout_marginTop="100px"
        android:background="#F0F0F0"
        android:gravity="center"
        android:text="@string/article"
        android:textColor="#E94D4D"
        android:textSize="32px"
        android:visibility="visible" />

    <TextView
        android:id="@+id/tv_frag_zl_author"
        android:layout_width="375px"
        android:layout_height="70px"
        android:layout_gravity="right"
        android:layout_marginTop="100px"
        android:background="#F0F0F0"
        android:gravity="center"
        android:text="@string/author_2"
        android:textColor="#333333"
        android:textSize="32px"
        android:visibility="visible" />

    <com.viewpagerindicator.UnderlinePageIndicator
        android:id="@+id/lpi_frag_zl"
        android:layout_width="match_parent"
        android:layout_height="4px"
        android:layout_marginTop="170px"
        android:background="#F0F0F0"
        app:fades="false"
        app:selectedColor="#E94D4D" />

    <android.support.v4.view.ViewPager
        android:id="@+id/vp_frag_zl"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="174px"
        android:background="@color/bg_gray"></android.support.v4.view.ViewPager>
</com.zhy.autolayout.AutoFrameLayout>

**Comment by ehaahe** [comment]
找到问题了，原来是viewpager里面的fragment的高度定死了的缘故

**Comment by hongyangAndroid** [comment]
恩，适当使用match_parent这类属性。
