### ISSUE TITLE
设计稿包括黑边吗

### ISSUE THREAD

**Issue by runningyz** [hongyangAndroid/AndroidAutoLayout#31]
假如一个手机分辨率720*1280 那么UI设计的时候 720*1280 这个范围是哪里到哪里 算不算手机黑边啊 manifest文件里该写720*1280还是设计稿的宽和高 还是没弄明白

**Comment by hongyangAndroid** [comment]
直接填设计稿的尺寸。

**Comment by runningyz** [comment]
嗯 谢谢鸿洋哥 大牛竟然这么亲民 再次感谢回复这么快

2015-12-17 22:37 GMT+08:00 张鸿洋 <notifications@github.com>:
