### ISSUE TITLE
出现大量的警告信息，希望能修正

### ISSUE THREAD

**Issue by ClareChen** [hongyangAndroid/AndroidAutoLayout#34]
12-23 13:28:53.387 22953-22953/com.zhy.sample W/Resources: Converting to string: TypedValue{t=0x10/d=0xffffffff a=-1}
12-23 13:28:53.397 22953-22953/com.zhy.sample W/Resources: Converting to string: TypedValue{t=0x10/d=0xffffffff a=-1}
12-23 13:28:53.397 22953-22953/com.zhy.sample W/Resources: Converting to string: TypedValue{t=0x5/d=0x8200 a=-1}
12-23 13:28:53.397 22953-22953/com.zhy.sample W/Resources: Converting to string: TypedValue{t=0x5/d=0x3400 a=-1}
12-23 13:28:53.407 22953-22953/com.zhy.sample W/Resources: Converting to string: TypedValue{t=0x10/d=0xfffffffe a=-1}
12-23 13:28:53.407 22953-22953/com.zhy.sample W/Resources: Converting to string: TypedValue{t=0x10/d=0xfffffffe a=-1}
12-23 13:28:53.407 22953-22953/com.zhy.sample W/Resources: Converting to string: TypedValue{t=0x10/d=0xfffffffe a=-1}

不清楚为什么会出现这么多将非String资源转成String的警告信息，很影响日志检索，希望能解决一下。

**Comment by hongyangAndroid** [comment]
fixed by #22 ,已经更新源码。
