### ISSUE TITLE
通过代码设置字号，无法适配

### ISSUE THREAD

**Issue by kaiyuanshengshichangan** [hongyangAndroid/AndroidAutoLayout#53]
发现通过代码设置字号无法进行适配，如何修改呢

**Comment by hongyangAndroid** [comment]
`textView.setText(AutoUtils. getPercentWidthSize(yourPxVal))`

**Comment by kaiyuanshengshichangan** [comment]
非常感谢，一会试下

**Comment by LymanHuang** [comment]
我已经解决了，下面代码可以适配字体大小

tv.setTextSize(TypedValue.COMPLEX_UNIT_PX, AutoUtils.getPercentWidthSize(yourPxVal));

tv.setTextSize(yourPxVal); // 默认使用的是sp
源码：
public void setTextSize(float size) {
      setTextSize(TypedValue.COMPLEX_UNIT_SP, size);
}

而我们要用px

**Comment by turbof** [comment]
我只是想讨论下哈，能不能设置字号的时候仍然使用sp，因为sp是谷歌官方推荐的设置字号的单位，当然，并不主要是因为这个我在平板上测试了下，可以看出来，autoLayout适配的方式是百分比，放大了字体，但是这样好像效果不是太好，反而使用sp的效果不错。

**Comment by LymanHuang** [comment]
要适配所有的屏幕的话也只能使用px了，那dp也是官方推荐的呢，反正我目前测试的情况是可行的。
ps : 刚刚看了下作者的源码，也是和我一样的方法，要想适配所有设备，只能使用px
`public class TextSizeAttr extends AutoAttr {
	public TextSizeAttr(int pxVal, int baseWidth, int baseHeight) {
		super(pxVal, baseWidth, baseHeight);
	}
	@Override
	protected int attrVal() {
		return Attrs.TEXTSIZE;
	}
	@Override
	protected boolean defaultBaseWidth() {
		return false;
	}
	@Override
	protected void execute(View view, int val) {
		if (!(view instanceof TextView))
			return;
		((TextView) view).setIncludeFontPadding(false);
                // 关键代码，使用px作为单位
		((TextView) view).setTextSize(TypedValue.COMPLEX_UNIT_PX, val);
	}
}`

**Comment by 244101430** [comment]
代码中改变字体大写这个问题怎么解决？

**Comment by 244101430** [comment]
代码中怎么解决字体大小？
tv.setTextSize(TypedValue.COMPLEX_UNIT_PX,400); 这代码没效果

**Comment by LymanHuang** [comment]
tv.setTextSize(TypedValue.COMPLEX_UNIT_PX, AutoUtils.getPercentWidthSize(yourPxVal));

要用AutoUtils.getPercentWidthSize(  yourpx  )，将你的px适配不同的屏幕，就ok了

**Comment by 244101430** [comment]
我代码和你写的一样也是没有效果？字体都没法动态改变，这个要解决？




------------------ 原始邮件 ------------------
发件人: "LymanHuang";<notifications@github.com>;
发送时间: 2016年2月19日(星期五) 下午4:11
收件人: "hongyangAndroid/AndroidAutoLayout"<AndroidAutoLayout@noreply.github.com>; 
抄送: "ブ流年、逝水"<244101430@qq.com>; 
主题: Re: [AndroidAutoLayout] 通过代码设置字号，无法适配 (#53)




tv.setTextSize(TypedValue.COMPLEX_UNIT_PX, AutoUtils.getPercentWidthSize(yourPxVal));
 
要用AutoUtils.getPercentWidthSize(  yourpx  )，将你的px适配不同的屏幕，就ok了

**Comment by kaiyuanshengshichangan** [comment]
代码中适配用这个
textView.setText(AutoUtils. getPercentWidthSize(yourPxVal))

**Comment by 244101430** [comment]
textView.setText();这个方法是设置内容的吧，不是改变字体大小




------------------ 原始邮件 ------------------
发件人: "kaiyuanshengshichangan";<notifications@github.com>;
发送时间: 2016年2月19日(星期五) 下午4:28
收件人: "hongyangAndroid/AndroidAutoLayout"<AndroidAutoLayout@noreply.github.com>; 
抄送: "ブ流年、逝水"<244101430@qq.com>; 
主题: Re: [AndroidAutoLayout] 通过代码设置字号，无法适配 (#53)




代码中适配用这个
 textView.setText(AutoUtils. getPercentWidthSize(yourPxVal))
