### ISSUE TITLE
在自定义view里面怎么进行适配呢

### ISSUE THREAD

**Issue by djjowfy** [hongyangAndroid/AndroidAutoLayout#54]
RT~

**Comment by djjowfy** [comment]
比如说自定义Imageview

**Comment by djjowfy** [comment]
好吧，我傻了。。。

**Comment by GeorgeBin** [comment]
@djjowfy 自定义控件怎么适配?为什么直接就关闭了?

**Comment by TimLoong** [comment]
可以考虑通过 将 与数值相关的值(如宽高,字号,padding,margin等) 与 AutoUtils.getPercentWidth1px() 相乘,保持不同尺寸比例一致.
