### ISSUE TITLE
Spinner 字体大小无法适配。

### ISSUE THREAD

**Issue by leveychen** [hongyangAndroid/AndroidAutoLayout#60]
设计稿 1080 * 1920
测试机 720 * 1280  / 1080 * 1920
Spinner 内部用Textview 设置 px 来控制大小，在720p上Spinner字体特大，其他字体完美自适应。
求解。

**Comment by hongyangAndroid** [comment]
参考 [https://github.com/hongyangAndroid/AndroidAutoLayout#扩展](https://github.com/hongyangAndroid/AndroidAutoLayout#扩展) 。

**Comment by leveychen** [comment]
非常抱歉，没有仔细阅读文档，自定义适配器，AutoSize一下就好了，感谢抽空回复
