### ISSUE TITLE
直接导入报下面问题  org/gradle/api/publication/maven/internal/DefaultMavenFactory

### ISSUE THREAD

**Issue by agoodcoolman** [hongyangAndroid/AndroidAutoLayout#74]
![112](https://cloud.githubusercontent.com/assets/11003275/14424420/81c1355a-0013-11e6-9418-ffb8e2b0ea6d.png)
Error:(2, 0) Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory
<a href="openFile:C:\Users\Administrator\Desktop\AndroidAutoLayout-master\autolayout\build.gradle">Open File</a>

**Comment by hongyangAndroid** [comment]
maven插件导致，这个插件是我用于上传的，你可以选择在build.gradle中删除该插件相关的配置信息（对比你自己项目有模块的build.gradle），此外这里还有个链接，可参考[https://github.com/hongyangAndroid/okhttp-utils/issues/24](https://github.com/hongyangAndroid/okhttp-utils/issues/24)

**Comment by agoodcoolman** [comment]
你这个秒回速度...真心赞...

**Comment by agoodcoolman** [comment]
提个建议:建议可以提供aar打包也可以.
对了.我直接在 build 中引用.会报
![112](https://cloud.githubusercontent.com/assets/11003275/14424564/65dda444-0014-11e6-8e25-dbcbce39c991.png)

**Comment by agoodcoolman** [comment]
@hongyangAndroid  在build中直接 compile 'com.zhy:autolayout:1.4.3'  应用,出现上面的问题

**Comment by hongyangAndroid** [comment]
你看一下你的compileSdkVersion和buildToolsVersion，这里的可参考配置是：

```
compileSdkVersion 23
buildToolsVersion "23.0.1"
```

**Comment by agoodcoolman** [comment]
好了.3Q,我刚才自己改了一下.就好了.

**Comment by qianrushi9** [comment]
compileSdkVersion 22 编译不过吗

**Comment by great-cause** [comment]
Error:(29, 13) Failed to resolve: com.zhy:autolayout:1.4.5
<a href="openFile:D:/shipei/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
