### ISSUE TITLE
这个button，在两个设备上不一样大。(768x1280，1080x1920)

### ISSUE THREAD

**Issue by swxca** [hongyangAndroid/AndroidAutoLayout#78]
![image](https://cloud.githubusercontent.com/assets/11407831/14909156/bd69657a-0e12-11e6-8ca4-d69aaa1c4bee.png)
![image](https://cloud.githubusercontent.com/assets/11407831/14909163/d08f902a-0e12-11e6-9fbd-9a9a1482b297.png)

**Comment by hongyangAndroid** [comment]
恩，首先这个库不是用来保证view在不同分辨率一样大的哈~ 如果你希望显示一样大，使用`dp`。

ok，下面说下这个库的表现，这个库主要是按照百分比去拉伸你设置的值，比如你宽度是150px，左图（768x1280）对应的实际显示宽度为：`150 *（768.0f/设计图宽度）`，而右图的宽度为：`150 *（1080f/设计图宽度）` 肯定是不同的，你可以点击打印宽度进行验证。

**Comment by swxca** [comment]
嗯嗯，是的。开始没看仔细，后来我就把issues关闭了。谢谢解答。
